### ISSUE TITLE
Release build Fails, Update lib to Android X

### ISSUE THREAD

**Issue by leen-nobbas** [roughike/flutter_facebook_login#93] opened 2019-02-13 22:48 UTC
Release build fails because android plugin needs to be updated to support `Android X`.
On `compileSdkVersion 28`.

Part of stack trace.
```
   /Users/gurleensethi/Documents/nobbas/nobbas-flutter/build/flutter_facebook_login/intermediates/res/compiled/release/values-zu_values-zu.arsc.flat\
          -R\
          /Users/gurleensethi/Documents/nobbas/nobbas-flutter/build/flutter_facebook_login/intermediates/res/compiled/release/drawable-mdpi-v4_abc_text_select_handle_right_mtrl_light.png.flat\
          -R\
          /Users/gurleensethi/Documents/nobbas/nobbas-flutter/build/flutter_facebook_login/intermediates/res/compiled/release/drawable_com_facebook_button_like_background.xml.flat\
          -R\
          /Users/gurleensethi/Documents/nobbas/nobbas-flutter/build/flutter_facebook_login/intermediates/res/compiled/release/drawable-xxhdpi-v4_abc_ab_share_pack_mtrl_alpha.9.png.flat\

```

**Comment by LatinaIsaac** [comment] 2019-02-15 07:30
same here

**Comment by LatinaIsaac** [comment] 2019-02-16 00:37
same

**Comment by kentcb** [comment] 2019-02-17 09:17
See #87

**Comment by roughike** [comment] 2019-02-23 10:36
Closing as a duplicate of #85.

**Closed by roughike** 2019-02-23 10:36 UTC
