### ISSUE TITLE
Release build failed (Debug works)

### ISSUE THREAD

**Issue by Jhon2524** [roughike/flutter_facebook_login#92] opened 2019-02-13 10:07 UTC
Using the package flutter_facebook_login, if I produce a debug apk everything works.
When I create a release apk it generates an error:

    What went wrong:
    Execution failed for task ':flutter_facebook_login:verifyReleaseResources'.
    > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
      C:\xxxx\flutter_facebook_login\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
      C:\xxxx\flutter_facebook_login\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
      C:\xxxx\flutter_facebook_login\intermediates\res\merged\release\values\values.xml:2779: error: resource android:attr/fontVariationSettings not found.
      C:\xxxx\flutter_facebook_login\intermediates\res\merged\release\values\values.xml:2780: error: resource android:attr/ttcIndex not found.
      error: failed linking references.

Thanks

**Comment by roughike** [comment] 2019-02-23 10:36
Closing as a duplicate of #85.

**Closed by roughike** 2019-02-23 10:36 UTC
