### ISSUE TITLE
flutter login crash

### ISSUE THREAD

**Issue by garbirel94** [roughike/flutter_facebook_login#165] opened 2019-08-24 09:37 UTC
Caused by: java.lang.IllegalStateException: 
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:135)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:225)
  at com.roughike.facebooklogin.facebooklogin.FacebookLoginResultDelegate.finishWithResult (FacebookLoginResultDelegate.java:58)
  at com.roughike.facebooklogin.facebooklogin.FacebookLoginResultDelegate.onSuccess (FacebookLoginResultDelegate.java:38)
  at com.roughike.facebooklogin.facebooklogin.FacebookLoginResultDelegate.onSuccess (FacebookLoginResultDelegate.java:13)
  at com.facebook.login.LoginManager.finishLogin (LoginManager.java:742)
  at com.facebook.login.LoginManager.onActivityResult (LoginManager.java:245)
  at com.facebook.login.LoginManager$1.onActivityResult (LoginManager.java:174)
  at com.facebook.internal.CallbackManagerImpl.onActivityResult (CallbackManagerImpl.java:91)
  at com.roughike.facebooklogin.facebooklogin.FacebookLoginResultDelegate.onActivityResult (FacebookLoginResultDelegate.java:53)
  at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:204)
  at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:132)
  at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:142)
  at android.app.Activity.dispatchActivityResult (Activity.java:6492)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:3925)

**Comment by a27919478** [comment] 2019-09-06 06:07
I also encountered this problem.

**Comment by garbirel94** [comment] 2019-09-06 06:10
have u solved it?

**Comment by garbirel94** [comment] 2019-09-06 06:10
> I also encountered this problem.

have u solved it?

**Comment by a27919478** [comment] 2019-09-06 06:16
> > I also encountered this problem.
> 
> have u solved it?

nope

**Comment by roughike** [comment] 2019-09-23 07:41
Closing as a duplicate of #55.

**Closed by roughike** 2019-09-23 07:41 UTC

**Comment by talhakhan011** [comment] 2020-07-15 09:21
facing same issue resolve it please
